# Generated by Django 5.0.2 on 2025-05-22 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0003_alumnos_maestros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='id_trabajador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('publico_objetivo', models.JSONField(default=list)),
                ('programa_educativo', models.CharField(blank=True, choices=[('ICC', 'Ingeniería en Ciencias de la Computación'), ('LCC', 'Licenciatura en Ciencias de la Computación'), ('ITI', 'Ingeniería en Tecnologías de la Información')], max_length=100, null=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
